CREATE TABLE documentos (
  id SERIAL PRIMARY KEY,
  tipo VARCHAR(20),
  numero_documento VARCHAR(50),
  registro_sgd VARCHAR(100),
  fecha_documento DATE,
  fecha_ingreso DATE,
  remitente VARCHAR(255),
  destinatario VARCHAR(255),
  asunto TEXT,
  area_responsable VARCHAR(255),
  nro_loe VARCHAR(100),
  incluye TEXT,
  cuenta VARCHAR(100),
  registro_entrada VARCHAR(100),
  fecha_recepcion DATE,
  plazo INTEGER,
  fecha_vencimiento DATE,
  alerta_dias INTEGER,
  fecha_respuesta DATE,
  archivo_url TEXT,
  estado VARCHAR(50),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);
